typography_spectrum: 0.8116
color:
  brandColors:
    - '#ffffff'
    - '#e6400e'
    - '#110302'
    - '#564941'
    - '#bababa'
  brandStrength: 1
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.90641
analytics:
  google: null
  facebook: null
  twitter: null
name: Ziegler's Hardware & Supply
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Electrical
    id: efcc80b2-2c15-4be0-bf85-0a740896b42e
    type: content
  - name: Plumbing
    id: 0b05a80b-b1b1-4ab9-8f7e-e84833bfd748
    type: content
  - name: "Paint\_"
    id: 647b7bae-ca1b-4c17-ab38-98cb93fb07da
    type: content
  - name: Contact Us
    id: 5558126b-b08c-4335-97ae-458dc20197cf
    type: content
favicon: null
title: Zieglers Hardware & Supply
purpose: []
