typography_spectrum: 0.8116
color:
  brandColors:
    - '#ffffff'
    - '#e6400e'
    - '#110302'
    - '#564941'
    - '#bababa'
  brandStrength: 1
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.90641
analytics:
  google: null
  facebook: null
  twitter: null
name: Ziegler's Hardware & Supply
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Electrical
    id: efcc80b2-2c15-4be0-bf85-0a740896b42e
    type: content
favicon: null
title: Zieglers Hardware & Supply
purpose: []
