name: Zieglers Hardware
favicon: null
layout_spectrum: 0.92312
typography_spectrum: 0.04588
title: "Ziegler's Hardware & Supply | "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e6400e'
    - '#110302'
    - '#564941'
    - '#bababa'
  brandStrength: 0.9375
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
