name: "Ziegler's Hardware & Supply"
favicon: null
layout_spectrum: 0.92312
typography_spectrum: 0.04588
title: "Ziegler's Hardware & Supply"
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e6400e'
    - '#110302'
    - '#564941'
    - '#bababa'
  brandStrength: 0.8920515
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
